# Generated by Django 4.2.24 on 2025-09-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='external_api_url',
            field=models.URLField(default='https://total-cms.worldws.pro//api'),
        ),
    ]
