# Generated by Django 4.2.26 on 2025-11-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_external_api_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='external_api_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='external_user_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_external_user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_login_api',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='token_expires_at',
        ),
    ]
