# Generated by Django 4.2.26 on 2025-11-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_customuser_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role_name',
            field=models.CharField(blank=True, choices=[('employe', 'Employé'), ('admin', 'Admin')], default='employe', max_length=255, null=True),
        ),
    ]
