# Generated by Django 4.2.24 on 2025-09-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='books/pdfs/', verbose_name='Fichier PDF'),
        ),
    ]
