# Generated by Django 4.2.24 on 2025-09-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL du PDF'),
        ),
    ]
