# Generated by Django 4.2.24 on 2025-09-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_pdf_file_book_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.TextField(blank=True, verbose_name='Contenu'),
        ),
    ]
