# Generated by Django 4.2.24 on 2025-09-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_thematique_chapter_thematique'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematique',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thematiques', to='books.book', verbose_name='Livre'),
            preserve_default=False,
        ),
    ]
