# Generated by Cascade helper
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_thematique_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='processing_status',
            field=models.CharField(
                choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('idle', 'Idle')],
                default='idle',
                max_length=32,
                verbose_name='Statut de traitement',
            ),
        ),
        migrations.AddField(
            model_name='book',
            name='processing_progress',
            field=models.PositiveIntegerField(default=0, verbose_name='Progression (%)'),
        ),
        migrations.AddField(
            model_name='book',
            name='processing_error',
            field=models.TextField(blank=True, null=True, verbose_name='Erreur de traitement'),
        ),
        migrations.AddField(
            model_name='book',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Début de traitement'),
        ),
        migrations.AddField(
            model_name='book',
            name='processing_finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de traitement'),
        ),
    ]
