# Generated by Django 4.2.26 on 2025-11-18 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_readingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('fr', 'Français'), ('en', 'Anglais'), ('pt', 'Portugais')], max_length=8, null=True, verbose_name='Langue détectée'),
        ),
        migrations.CreateModel(
            name='ThematiqueTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=8)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('stale', 'Stale')], default='pending', max_length=16)),
                ('source_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thematique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='books.thematique')),
            ],
            options={
                'unique_together': {('thematique', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='SubsectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=8)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('tables', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('stale', 'Stale')], default='pending', max_length=16)),
                ('source_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='books.subsection')),
            ],
            options={
                'unique_together': {('subsection', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='SectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=8)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('tables', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('stale', 'Stale')], default='pending', max_length=16)),
                ('source_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='books.section')),
            ],
            options={
                'unique_together': {('section', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='ChapterTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=8)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('stale', 'Stale')], default='pending', max_length=16)),
                ('source_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='books.chapter')),
            ],
            options={
                'unique_together': {('chapter', 'lang')},
            },
        ),
    ]
