# Generated by Django 4.2.26 on 2025-11-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_language_thematiquetranslation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publié'),
        ),
    ]
