# Generated by Django 4.2.26 on 2025-11-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_intro',
            field=models.BooleanField(default=False, verbose_name="Chapitre d'introduction"),
        ),
    ]
