# Generated by Django 4.2.26 on 2025-11-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_chapter_is_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='tables',
            field=models.JSONField(blank=True, default=list, verbose_name='Tableaux'),
        ),
    ]
